---
name: Container

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:

permissions:
  contents: read
  packages: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  image:
    name: Build image
    uses: abhi1693/actions/.github/workflows/docker-build-push.yml@master
    with:
      runs-on: ubuntu-24.04-arm
      image: ghcr.io/${{ github.repository }}
      context: .
      file: Dockerfile
      platforms: linux/arm64
      cache-scope: qbittorrent-smart-queues
      push: ${{ github.event_name != 'pull_request' }}
      tags: |
        type=ref,event=branch
        type=ref,event=tag
        type=semver,pattern={{version}}
        type=sha,prefix=sha-
      labels: |
        org.opencontainers.image.source=https://github.com/${{ github.repository }}
        org.opencontainers.image.title=qbittorrent-smart-queues
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
